---
dist: xenial

language: python
python:
  - "3.8"

env:
  - DOCKER_COMPOSE_VERSION=1.4.2

services:
  - docker

before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose-bin
  - chmod +x docker-compose-bin
  - sudo mv docker-compose-bin /usr/local/bin

install:
  - pip install -r requirements.txt

script:
- cd docker-compose up -d && cd ..
- python test.py