version: '3'

networks:
  redis-sentinel:
    driver: bridge

services:
  redis-master:
    image: 'bitnami/redis:5.0-debian-9'
    ports:
      - '6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_EXTRA_FLAGS=--maxmemory 200mb
    volumes:
      - 'redis-master-volume:/bitnami'
    networks:
      redis-sentinel:

  redis-sentinel-0:
    image: 'bitnami/redis:5.0-debian-9'
    ports:
      - '16379'
    depends_on:
      - redis-master
    volumes:
      - 'redis-sentinel-volume:/bitnami'
    entrypoint: |
      bash -c 'bash -s <<EOF
      "/bin/bash" -c "cat <<EOF > /opt/bitnami/redis/etc/sentinel.conf
      port 16379
      dir /tmp
      sentinel monitor master-node redis-master 6379 2
      sentinel down-after-milliseconds master-node 5000
      sentinel parallel-syncs master-node 1
      sentinel failover-timeout master-node 5000
      EOF"
      "/bin/bash" -c "redis-sentinel /opt/bitnami/redis/etc/sentinel.conf"    
      EOF'
    networks:
      redis-sentinel:

  redis-sentinel-1:
    image: 'bitnami/redis:5.0-debian-9'
    ports:
      - '16379'
    depends_on:
      - redis-master
    volumes:
      - 'redis-sentinel-volume:/bitnami'
    entrypoint: |
      bash -c 'bash -s <<EOF
      "/bin/bash" -c "cat <<EOF > /opt/bitnami/redis/etc/sentinel.conf
      port 16379
      dir /tmp
      sentinel monitor master-node redis-master 6379 2
      sentinel down-after-milliseconds master-node 5000
      sentinel parallel-syncs master-node 1
      sentinel failover-timeout master-node 5000
      EOF"
      "/bin/bash" -c "redis-sentinel /opt/bitnami/redis/etc/sentinel.conf"    
      EOF'
    networks:
      redis-sentinel:

  redis-sentinel-2:
    image: 'bitnami/redis:5.0-debian-9'
    ports:
      - '16379'
    depends_on:
      - redis-master
    volumes:
      - 'redis-sentinel-volume:/bitnami'
    entrypoint: |
      bash -c 'bash -s <<EOF
      "/bin/bash" -c "cat <<EOF > /opt/bitnami/redis/etc/sentinel.conf
      port 16379
      dir /tmp
      sentinel monitor master-node redis-master 6379 2
      sentinel down-after-milliseconds master-node 5000
      sentinel parallel-syncs master-node 1
      sentinel failover-timeout master-node 5000
      EOF"
      "/bin/bash" -c "redis-sentinel /opt/bitnami/redis/etc/sentinel.conf"    
      EOF'
    networks:
      redis-sentinel:

  redis-slave:
    image: 'bitnami/redis:5.0-debian-9'
    ports:
      - '6379'
    depends_on:
      - redis-master
    volumes:
      - 'redis-slave-volume:/bitnami'
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_EXTRA_FLAGS=--maxmemory 200mb
    networks:
      redis-sentinel:

  redis-exporter:
    image: bitnami/redis-exporter:1
    ports:
      - '9121:9121'
    depends_on:
      - redis-master
      - redis-slave
    networks:
      redis-sentinel:

  haproxy:
    image: 'haproxy:2.1.0-alpine'
    volumes:
      - ./haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '8080:8080'
      - '6379:6379'
    depends_on:
      - redis-sentinel-0
      - redis-sentinel-1
      - redis-sentinel-2
    networks:
      redis-sentinel:

  redis-script-python:
    image: hrvoje6/redis-script-python:latest
    depends_on:
      - redis-master
      - redis-slave
      - haproxy
    environment:
      - REDIS_HOST=haproxy
    entrypoint:
      - /bin/sh
      - -c
      - |
        python /app/cli.py set_keys
        python /app/cli.py watch_keys
    networks:
      redis-sentinel:

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    depends_on:
      - redis-exporter
    volumes:
      - ./prom-sentinel.yml:/etc/prometheus/prometheus.yml
      - prometheus-data-volume:/prometheus
    networks:
      redis-sentinel:

  grafana:
    image: grafana/grafana
    user: "104"
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - ./provisioning-grafana/:/etc/grafana/provisioning/
      - 'grafana-data-volume:/var/lib/grafana'
    networks:
      redis-sentinel:

volumes:
  redis-master-volume:
  redis-slave-volume:
  redis-sentinel-volume:
  grafana-data-volume:
  prometheus-data-volume: