version: '3'

networks:
  redis-cluster:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/16

services:
  redis-0:
    image: 'redis:5.0.7-alpine'
    ports:
      - '7000:7000'
    volumes:
      - 'redis-vol-0:/bitnami'
      - ./cluster-config-0.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.2

  redis-1:
    image: 'redis:5.0.7-alpine'
    ports:
      - '7001:7001'
    depends_on:
      - redis-0
    volumes:
      - 'redis-vol-1:/bitnami'
      - ./cluster-config-1.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.3

  redis-2:
    image: 'redis:5.0.7-alpine'
    ports:
      - '7002:7002'
    depends_on:
      - redis-1
    volumes:
      - 'redis-vol-2/bitnami'
      - ./cluster-config-2.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.4

  redis-3:
    image: 'redis:5.0.7-alpine'
    ports:
      - '7003:7003'
    depends_on:
      - redis-2
    volumes:
      - 'redis-vol-3:/bitnami'
      - ./cluster-config-3.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.5

  redis-4:
    image: 'redis:5.0.7-alpine'
    ports:
      - '7004:7004'
    depends_on:
      - redis-3
    volumes:
      - 'redis-vol-4:/bitnami'
      - ./cluster-config-4.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.6

  redis-5:
    image: 'redis:5.0.7-alpine'
    ports:
      - '7005:7005'
    depends_on:
      - redis-4
    volumes:
      - 'redis-vol-5:/bitnami'
      - ./cluster-config-5.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.7

  haproxy:
    image: 'haproxy:2.1.0-alpine'
    volumes:
      - ./haproxy_6_nodes.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    ports:
      - '8080:8080'
      - '6379:6379'
    depends_on:
      - redis-0
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.8

  redis-script-python:
    image: hrvoje6/redis-script-python:latest
    depends_on:
      - redis-0
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
      - haproxy
    environment:
      - REDIS_HA=CLUSTER
      - REDIS_HOST=10.0.0.2:7000,10.0.0.3:7001,10.0.0.4:7002
    entrypoint:
      - /bin/sh
      - -c
      - |
        python /app/cli.py set_keys
        python /app/cli.py watch_keys
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.9

  redis-exporter:
    image: bitnami/redis-exporter:1
    ports:
      - '9122:9121'
    depends_on:
      - redis-0
      - redis-1
      - redis-2
      - redis-3
      - redis-4
      - redis-5
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.10

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    depends_on:
      - redis-exporter
    volumes:
      - ./prom-cluster.yml:/etc/prometheus/prometheus.yml
      - prometheus-data-volume:/prometheus
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.11

  grafana:
    image: grafana/grafana
    user: "104"
    ports:
      - '3000:3000'
    depends_on:
      - prometheus
    volumes:
      - ./provisioning-grafana/:/etc/grafana/provisioning/
      - 'grafana-data-volume:/var/lib/grafana'
    networks:
      redis-cluster:
        ipv4_address: 10.0.0.12

volumes:
  redis-vol-0:
  redis-vol-1:
  redis-vol-2:
  redis-vol-3:
  redis-vol-4:
  redis-vol-5:
  prometheus-data-volume:
  grafana-data-volume: