global:
  scrape_interval:     6s
  evaluation_interval: 6s


scrape_configs:
  - job_name: 'redis_exporter_targets'
    static_configs:
      - targets:
        - redis://redis-master:6379
        - redis://redis-slave:6379
    metrics_path: /scrape
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: redis-exporter:9121
  
  - job_name: 'redis_exporter'
    static_configs:
      - targets:
        - redis-exporter:9121